### PR TITLE
Improve Webpages

### PR DESCRIPTION
**Pull request by HimDek**
I was improving the polonium webpages. I hope you like it.

### Highlights
* All pages have a common header, footer and navbar.
* Each individual page parses the corresponding markdown file that already exists and displays them.
* Easy to extend.

View the page [here](https://himdek.com/polonium/).

The home page is unable to display the icon in my deployement because it uses the [readme.md](https://github.com/zeroxoneafour/polonium/blob/master/readme.md) file from [zeroxoneafour:master](https://github.com/zeroxoneafour/polonium/tree/master) branch which is obviously unchanged. The icon will be visisble once this request is pulled.

### CODE REVIEW

**Comment by zeroxoneafour** [comment]
This looks incredible! Thank you so much for this redesign.

**Comment by HimDek** [comment]
> This looks incredible! Thank you so much for this redesign.

My pleasure. By the way, it seems you are using [zeroxoneafour:stable](https://github.com/zeroxoneafour/polonium/tree/stable) branch for building the page which is why the changes are not deployed.

**Comment by zeroxoneafour** [comment]
I'm aware, I branched off stable so that the docs would be relevant to the version most users are using. I'll merge master back into it later tonight.

**Comment by HimDek** [comment]
In that case, the `master` in the below line must be changed to the name of the branch you wish to deploy the page from.
https://github.com/zeroxoneafour/polonium/blob/d24fb0b2bba1755f9f11f261e670a8822a912827/docs/index.html#L22

**Pull request merged**
